name: CI-debug
on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

jobs:
  openEuler-latest-cmake-cann:
    if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
    defaults:
      run:
        shell: bash -el {0}
    runs-on: ubuntu-24.04-arm
    strategy:
      matrix:
        cann:
          - '8.0.rc3.beta1-910b-openeuler22.03-py3.10'
        device:
          - 'ascend910b3'
        build:
          - 'Release'
    container: ascendai/cann:${{ matrix.cann }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Dependencies
        run: |
          yum update -y
          yum install -y git gcc gcc-c++ make cmake

      - name: Enable debug logging
        if: ${{ inputs.debug_enabled == true }}
        run: |
          echo "ACTIONS_RUNNER_DEBUG=true" >> $GITHUB_ENV
          echo "ACTIONS_STEP_DEBUG=true" >> $GITHUB_ENV

      - name: Setup tmate session
        uses: lovemefan/action-tmate@v1.1
